### PR TITLE
Added GitHub action to automatically build PyTTa distribution package. If it succeeds, it is uploaded to PyPI

### PR DESCRIPTION
**Pull request by jvcarli**
Currently PyTTa version from PyPI repository is too distant from the GitHub repo. This problem is addressed with a GitHub action. There is a full explanation at `.github/workflows/README.md`

### CODE REVIEW

**Comment by jvcarli** [comment]
At https://pypi.org/project/pytta-deploy-test/ there's an example of PyTTa where the build and deploy was fully automated by this workflow. I will delete it latter.

**Comment by Chum4k3r** [comment]
To my understanding, it is really useful to have some automations, although this one would imply that each and every modification commited to this branch would automatically update PyPI, which, in it's side, would only accept uploads from new versions, which would then imply that for the automation to work, every push to GitHub must have a new version number on setup.py file.

Deploying the software continously is not what I see as a higher priority right now, since we are currently on heavy documentation process and we don't have (yet) a contribution workflow that can address the update-version-before-push process that this automation requires.

This rolling versioning wasn't the original plan, but it indeed is a way of versioning software, and lots of open source projects work like this. Still, good guidelines on how to contribute with code are needed to have a better understanding of which versioning fits PyTTa better.

**Review by Chum4k3r — COMMENTED** [review]
Very good explanation on README.md

The build-publish-to-pypi.yml file would not require any changes, right? Just setting up the PyTTaMaster secrets for PyPI?

Very good contibution, thanks!
Will wait for @mtslazarin review.

**Comment by jvcarli** [comment]
I'm glad to hear that! You're right, the only thing needed is to setup PyTTaMaster secrets for PyPI and it should be good to go.

**Review by mtslazarin — COMMENTED** [review]
As only tagged commits triggers the update on pip I think It's a fantastic contribution! Thanks @jvitorcarli 
Looks some actions are demanded on the repository-adm-side. @Chum4k3r , can u take care of it?

**Comment by PyTTaMaster** [comment]
@jvitorcarli , one more consideration. Only the most stable version should go to pip. For now, we could tag the most recent beta version. After v0.1.0 we won't tag beta versions anymore (hell yeah).

**Pull request merged**
